### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/bridge#30]
[Design System Link](https://www.notion.so/h4iuiuc/Hack4Impact-s-Design-System-Bridge-40aaae97c71f400084b4bbcc5cd8cdee#934e3ffe3d424ed4803bc9c147f1a37c)

need to ensure styling matches with `<thead>`, `<tr>`, `<th>`, `<td>`.. not sure whether they sure inherit whatever the font the table is in? 

### Props
- `type`: `primary`, `borderless`, `zebra`

**Comment by dl-eric** [comment]
Taking this!

What should the width of the table be? The mocks kind of imply that it just wraps its children, but I wanted to be sure because it might make sense for it to fill the width of its parent (i.e width: 100%)

Current storyboard screenshot:
![image](https://user-images.githubusercontent.com/11535201/81945249-78702c00-95c3-11ea-8782-109063bc4bdc.png)

playground.js:
`<Table type="primary">
          <TableHead>
            <TableRow>
              <TableCell>First Name</TableCell>
              <TableCell>Last Name</TableCell>
              <TableCell>Favorite Color</TableCell>
              <TableCell>Favorite Number</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>Chloe</TableCell>
              <TableCell>Chan</TableCell>
              <TableCell>Pink</TableCell>
              <TableCell>3</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Ashley</TableCell>
              <TableCell>Chan</TableCell>
              <TableCell>Blue</TableCell>
              <TableCell>7</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Nicole</TableCell>
              <TableCell>Nguyen</TableCell>
              <TableCell>Red</TableCell>
              <TableCell>10</TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <Table type="borderless">
          <TableHead>
            <TableRow>
              <TableCell>First Name</TableCell>
              <TableCell>Last Name</TableCell>
              <TableCell>Favorite Color</TableCell>
              <TableCell>Favorite Number</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>Chloe</TableCell>
              <TableCell>Chan</TableCell>
              <TableCell>Pink</TableCell>
              <TableCell>3</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Ashley</TableCell>
              <TableCell>Chan</TableCell>
              <TableCell>Blue</TableCell>
              <TableCell>7</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Nicole</TableCell>
              <TableCell>Nguyen</TableCell>
              <TableCell>Red</TableCell>
              <TableCell>10</TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <Table type="zebra">
          <TableHead>
            <TableRow>
              <TableCell>First Name</TableCell>
              <TableCell>Last Name</TableCell>
              <TableCell>Favorite Color</TableCell>
              <TableCell>Favorite Number</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>Chloe</TableCell>
              <TableCell>Chan</TableCell>
              <TableCell>Pink</TableCell>
              <TableCell>3</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Ashley</TableCell>
              <TableCell>Chan</TableCell>
              <TableCell>Blue</TableCell>
              <TableCell>7</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Nicole</TableCell>
              <TableCell>Nguyen</TableCell>
              <TableCell>Red</TableCell>
              <TableCell>10</TableCell>
            </TableRow>
          </TableBody>
        </Table>`

**Comment by tko22** [comment]
dope! could you assign yourself to the issue? 

- yep, I would make the table expand to the width of its parent. 
- For Table specific components, could you do <Table.Row/ >, <Table.Cell/> etc I would follow https://github.com/hack4impact-uiuc/bridge/blob/master/src/components/Card/Card.js
- for <Table />, I would also set the default typography styles (typography.tables) and then table specific components will inherit the font.. but say for TableHead, font-weight will be bold

**Comment by dl-eric** [comment]
I can't assign myself :(

**Comment by dl-eric** [comment]
Ty jq!
